# Generated by Django 3.2.6 on 2023-10-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudad', '0001_create_table_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('latitud', models.CharField(max_length=250)),
                ('longitud', models.CharField(max_length=250)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudad.ciudad')),
            ],
            options={
                'db_table': 'paradas',
            },
        ),
    ]
