# Generated by Django 3.2.6 on 2023-10-19 20:25

from django.db import migrations, models
from ciudad.models.Ciudad import Ciudad

def cargar_ciudades(apps, schema_editor):
    ciudad = Ciudad(nombre='Bogota')
    ciudad.save()

    ciudad = Ciudad(nombre='Medellin')
    ciudad.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.RunPython(cargar_ciudades),
    ]
