# Generated by Django 3.2.6 on 2023-10-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paradas', '0001_create_table_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ruta',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField()),
                ('hora_llegada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradas.paradas')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
    ]
